const vietnameseDistricts = [
    'quận 1',
    'quận 2',
    'quận 3',
    'quận 4',
    'quận 5',
    'quận 6',
    'quận 7',
    'quận 8',
    'quận 9',
    'quận 10',
    'quận 11',
    'quận 12',
    'quận bình thạnh',
    'quận gò vấp',
    'quận phú nhuận',
    'quận tân bình',
    'quận tân phú',
    'quận thủ đức',
    'huyện bình chánh',
    'huyện cần giờ',
    'huyện củ chi',
    'huyện hóc môn',
    'huyện nhà bè',
    'quận ba đình',
    'quận cầu giấy',
    'quận đống đa',
    'quận hà đông',
    'quận hai bà trưng',
    'quận hoàn kiếm',
    'quận hoàng mai',
    'quận long biên',
    'quận tây hồ',
    'quận thanh xuân',
    'thị xã sơn tây',
    'huyện ba vì',
    'huyện chương mỹ',
    'huyện đan phượng',
    'huyện đông anh',
    'huyện gia lâm',
    'huyện hoài đức',
    'huyện mê linh',
    'huyện mỹ đức',
    'huyện phú xuyên',
    'huyện phúc thọ',
    'huyện quốc oai',
    'huyện sóc sơn',
    'huyện thạch thất',
    'huyện thanh oai',
    'huyện thanh trì',
    'huyện thường tín',
    'huyện ứng hòa'
];
export default vietnameseDistricts