const vietnameseProvinces = [
    'hà nội',
    'hồ chí minh',
    'đà nẵng',
    'hải phòng',
    'cần thơ',
    'an giang',
    'bà rịa - vũng tàu',
    'bắc giang',
    'bắc kạn',
    'bạc liêu',
    'bắc ninh',
    'bến tre',
    'bình định',
    'bình dương',
    'bình phước',
    'bình thuận',
    'cà mau',
    'cao bằng',
    'đắk lắk',
    'đắk nông',
    'điện biên',
    'đồng nai',
    'đồng tháp',
    'gia lai',
    'hà giang',
    'hà nam',
    'hà tĩnh',
    'hải dương',
    'hậu giang',
    'hòa bình',
    'hưng yên',
    'khánh hòa',
    'kiên giang',
    'kon tum',
    'lai châu',
    'lâm đồng',
    'lạng sơn',
    'lào cai',
    'long an',
    'nam định',
    'nghệ an',
    'ninh bình',
    'ninh thuận',
    'phú thọ',
    'phú yên',
    'quảng bình',
    'quảng nam',
    'quảng ngãi',
    'quảng ninh',
    'quảng trị',
    'sóc trăng',
    'sơn la',
    'tây ninh',
    'thái bình',
    'thái nguyên',
    'thanh hóa',
    'thừa thiên huế',
    'tiền giang',
    'trà vinh',
    'tuyên quang',
    'vĩnh long',
    'vĩnh phúc',
    'yên bái'
];
  export default vietnameseProvinces